// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ic2X0-Im_cyCVkCpOqDY_hAkxrM2hyY',
    appId: '1:895866284056:web:f5ac57ab1cd326ddcabb6d',
    messagingSenderId: '895866284056',
    projectId: 'yerimcep',
    authDomain: 'yerimcep.firebaseapp.com',
    storageBucket: 'yerimcep.firebasestorage.app',
    measurementId: 'G-KCNHDV0FZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeImjfvDx-7EHd_gRPL3AbZpCKXnx0JCU',
    appId: '1:895866284056:android:13247f6b3ccc567ecabb6d',
    messagingSenderId: '895866284056',
    projectId: 'yerimcep',
    storageBucket: 'yerimcep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMxWehoFul-waBxJSuWDGsMenACJdz54E',
    appId: '1:895866284056:ios:f25d5574a6a7d77acabb6d',
    messagingSenderId: '895866284056',
    projectId: 'yerimcep',
    storageBucket: 'yerimcep.firebasestorage.app',
    iosBundleId: 'com.example.yerimcep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMxWehoFul-waBxJSuWDGsMenACJdz54E',
    appId: '1:895866284056:ios:f25d5574a6a7d77acabb6d',
    messagingSenderId: '895866284056',
    projectId: 'yerimcep',
    storageBucket: 'yerimcep.firebasestorage.app',
    iosBundleId: 'com.example.yerimcep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ic2X0-Im_cyCVkCpOqDY_hAkxrM2hyY',
    appId: '1:895866284056:web:8d4cb17c3f62d2b8cabb6d',
    messagingSenderId: '895866284056',
    projectId: 'yerimcep',
    authDomain: 'yerimcep.firebaseapp.com',
    storageBucket: 'yerimcep.firebasestorage.app',
    measurementId: 'G-TJ80K3DKQC',
  );

}